name: Delete build test

on:
  push:
    branches-ignore: 
      - master
    paths:
      - 'Frends.MongoDB.Index/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.MongoDB.Index
      prebuild_command: docker-compose -f ./Frends.MongoDB.Index.Tests/Files/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}